name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: pnpm install
      - name: build project
        run: pnpm run build
      - name: format project
        run: pnpm run format
      - name: lint project
        run: pnpm run lint
      - name: preview project
        run: pnpm run preview
      - name: build-storybook project
        run: pnpm run build-storybook
      - name: storybook project
        run: pnpm run storybook